// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpsxwzvkdflxqcdfcllw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwc3h3enZrZGZseHFjZGZjbGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mzg1OTYsImV4cCI6MjA3MzMxNDU5Nn0.yqm0WwugmNDdkvl27aE76vsezw55Jxvi-xj1ILtpFFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});